
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 06 14:12:30 CDT 2022
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VERFRUTA = 10;
  public static final int ABAJO = 6;
  public static final int ARRIBA = 5;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 7;
  public static final int NUMERO = 13;
  public static final int LLAVEC = 12;
  public static final int LLAVEA = 11;
  public static final int DERECHA = 8;
  public static final int error = 1;
  public static final int COLOCA = 3;
  public static final int MOVER = 4;
  public static final int PUNTOYCOMA = 2;
  public static final int REPETIR = 9;
}

